FROM golang:1.22

RUN apt-get update && apt-get install -y \
    protobuf-compiler=3.21.\* \
    && apt-get clean

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.35.1 \
    && go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1

ENTRYPOINT ["protoc"]
CMD ["--help"]